// Generated by CoffeeScript 1.6.3
var Classmate, School, async, fs, im, mongoose, passport;

passport = require('passport');

mongoose = require('mongoose');

async = require('async');

fs = require('fs');

im = require('imagemagick');

School = mongoose.model('School');

Classmate = mongoose.model('Classmate');

exports.create = function(req, res) {
  var classmate, errors, photo;
  photo = req.files.photo;
  req.assert('firstName', 'Please enter a first name').notEmpty();
  req.assert('lastName', 'Please enter a last name').notEmpty();
  errors = req.validationErrors(true);
  if (!errors) {
    classmate = new Classmate(req.body);
    classmate.save(function(err) {
      var tempPath, thumbPath;
      if (!err) {
        tempPath = '/home/efuentesp/development/peacemakers/uploads/temp/' + classmate.id + '.jpg';
        thumbPath = '/home/efuentesp/development/peacemakers/uploads/thumb/' + classmate.id + '.jpg';
        async.series({
          resizePhoto: function(done) {
            return fs.readFile(photo.path, function(err, data) {
              return fs.writeFile(tempPath, data, function(err) {
                return im.resize({
                  srcPath: tempPath,
                  dstPath: thumbPath,
                  width: 100,
                  height: 120
                }, function(err, stdout, stderr) {
                  if (err) {
                    done(err);
                  }
                  return done();
                });
              });
            });
          },
          deletePhoto: function(done) {
            return fs.unlinkSync(tempPath);
          }
        });
        return res.send(classmate);
      } else {
        console.log(err);
        res.statusCode = 500;
        return res.send("Error 500: Internal Server Error found!");
      }
    });
    return res.send(classmate);
  } else {
    res.statusCode = 400;
    return res.send(errors);
  }
};
