// Generated by CoffeeScript 1.6.3
var School, mongoose, passport;

passport = require('passport');

mongoose = require('mongoose');

School = mongoose.model('School');

exports.list = function(req, res) {
  console.log("GET: " + req.params);
  return School.findById(req.params.school, function(err, school) {
    var period, stage;
    if (!err) {
      if (school) {
        stage = school.stages.id(req.params.school);
        period = stage.id(req.params.period);
        return res.send(period.classes);
      } else {
        console.log("Resource not found!");
        res.statusCode = 400;
        return res.send("Error 400: Resource not found!");
      }
    } else {
      return console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
  });
};

exports.create = function(req, res) {
  var errors;
  req.assert('name', 'Please enter a name').notEmpty();
  errors = req.validationErrors(true);
  if (!errors) {
    return School.findById(req.params.school, function(err, school) {
      var cls, period, stage;
      if (!err) {
        if (school) {
          stage = school.stages.id(req.params.stage);
          period = stage.periods.id(req.params.period);
          cls = period.classes.addToSet(req.body);
          return school.save(function(err) {
            if (!err) {
              return res.send(school.stages.id(req.params.stage).periods.id(req.params.period).classes[period.classes.length - 1]);
            } else {
              console.log(err);
              res.statusCode = 500;
              return res.send("Error 500: Internal Server Error found!");
            }
          });
        } else {
          console.log("Resource not found!");
          res.statusCode = 400;
          return res.send("Error 400: Resource not found!");
        }
      } else {
        return console.log(err);
        res.statusCode = 500;
        return res.send("Error 500: Internal Server Error found!");
      }
    });
  } else {
    console.log(errors);
    res.statusCode = 400;
    return res.send(errors);
  }
};
