// Generated by CoffeeScript 1.6.3
var ClassSchema, PeriodSchema, Schema, SchoolSchema, StageSchema, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

PeriodSchema = new Schema({
  name: {
    type: String,
    "default": ''
  },
  classes: [ClassSchema]
});

StageSchema = new Schema({
  name: {
    type: String,
    "default": ''
  },
  periods: [PeriodSchema],
  createdAt: {
    type: Date,
    "default": Date.now
  }
});

ClassSchema = new Schema({
  name: {
    type: String,
    "default": ''
  },
  createdAt: {
    type: Date,
    "default": Date.now
  }
});

SchoolSchema = new Schema({
  name: {
    type: String,
    "default": ''
  },
  www: {
    type: String,
    "default": ''
  },
  stages: [StageSchema],
  createdAt: {
    type: Date,
    "default": Date.now
  }
});

mongoose.model('School', SchoolSchema);

mongoose.model('Stage', StageSchema);

mongoose.model('Period', PeriodSchema);

mongoose.model('Class', ClassSchema);
